### ISSUE TITLE
Update the documentation for Mac

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#76]
@GuillaumeUnice @Kan23 : Please Update the documentation for Dev Mac based on Dev Linux Documentation. 

Ask to @cvandome to play it.

**Comment by GuillaumeUnice** [comment]
Hi, @cvandome have test on OSX El Capitan:.

First of all, the dnsmasq there the following command don't work or it's obsolete
`sudo launchctl start homebrew.mxcl.dnsmasq`

The official documentation should make a link with LaunchDaemons directory and then run service like this
```
sudo cp -v $(brew --prefix dnsmasq)/homebrew.mxcl.dnsmasq.plist /Library/LaunchDaemons
sudo launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
```

Then, there is a command in order to update node in latest version
`cd $HOME/cloudUnit/cu-manager/src/main/webapp && sudo n stable`

But I think this command is useless because just before there is a link to install node. Their is 3 choices : 
-Remove this command
-Place this command just before install in optional
-Keep this command

Finally, I think it's important to rewrite at the end the default login & password?

**Comment by GuillaumeUnice** [comment]
All is in the [pull request 78](https://github.com/Treeptik/cloudunit/pull/78)
